In [5]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv('../data/Bengaluru_House_Data.csv')

In [16]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [17]:
df.shape

(13320, 9)

In [18]:
df.sample(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
4428,Super built-up Area,Ready To Move,BEML Layout,3 BHK,NaN,2000,2.0,2.0,85.00
9533,Super built-up Area,Ready To Move,Yeshwanthpur,3 BHK,IBityin,1384,2.0,2.0,76.18
3406,Super built-up Area,18-Apr,Kothannur,3 BHK,NaN,1270,3.0,2.0,45.00
4549,Super built-up Area,18-May,BTM 2nd Stage,3 BHK,NaN,1250,3.0,1.0,50.00
12583,Super built-up Area,18-Apr,Hormavu,3 BHK,NaN,1166,2.0,2.0,34.97

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  str
 1   availability  13320 non-null  str
 2   location      13319 non-null  str
 3   size          13304 non-null  str
 4   society       7818 non-null   str
 5   total_sqft    13320 non-null  str
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), str(6)
memory usage: 1.6 MB

In [25]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [26]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [27]:
df.duplicated().sum()

np.int64(529)

In [28]:
df.drop_duplicates()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00

In [31]:
df.rename(columns={"price": "price(in lakhs)", "bath": "bathrooms"}, inplace=True)

In [32]:
df.sample(5)

,area_type,availability,location,size,society,total_sqft,bathrooms,balcony,price(in lakhs)
11060,Plot Area,Ready To Move,Margondanahalli,3 Bedroom,NaN,1448,3.0,1.0,70.0
10100,Built-up Area,Ready To Move,Uttarahalli,2 BHK,NaN,1200,2.0,1.0,55.0
2681,Super built-up Area,21-Dec,Thanisandra,1 BHK,Bhe 2ko,693,1.0,1.0,34.3
3273,Super built-up Area,Ready To Move,Kaggalipura,2 BHK,Baowsig,950,2.0,1.0,48.0
352,Carpet Area,Ready To Move,Sampigehalli,3 BHK,Puens G,1592,3.0,2.0,75.0